@startuml

title NTier Architecture

package "Server" {
 [Router] <--> [Controller]
 [Controller] <--> [Service]
 [Service] <--> [DAO]
 [DAO]
 [Model]

 [Service]  -- [Model]
}

cloud "Private Network" {
    [LAN]
}

database "Storage" {
 [MongoDB]
}

[HTTP] <--> [Router]
[DAO] <--> [LAN]
[LAN] <--> [MongoDB]



@enduml

